### ISSUE TITLE
Member Types and Statuses

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-directory#1]
Out of the box CiviMember does not provide any Member Types, it's blank. So each instance of CiviCRM will have it's own naming and options of member types. 

Statues are as seen here, but can be extended too. 

![membership-status-rules](https://user-images.githubusercontent.com/1139085/30116905-ba659c3a-92ec-11e7-95de-c9ee550c00d2.png)

Are there any other specifics on this that would be helpful?

**Comment by danaskallman** [comment]
In terms of MVP, if #2 is simpler I'd start there since it provides more flexibility and doesn't require the use of CiviMember. Not all directories would be based on membership. Could be contact type, or relationship...anything the mind can think of really.

**Comment by christianwach** [comment]
I think the current version of the plugin satisfies most of the criteria in this ticket because any kind of CiviCRM group can be the basis of a Directory - and since a Smart Group's members can be based on any criteria that CiviCRM allows (which includes Memberships and their Statuses) this means that the Smart Group (and therefore the Directory) should be able to accommodate this kind of filtering.

Let me know if I've missed something or misunderstood Smart Groups.

**Comment by danaskallman** [comment]
Yeah, agreed. I think this covers what's needed and if anything new comes up we can link issue and start a new one based on whatever criteria that may be.
